// Auto-generated by make — do not edit
let buildVersion = "1.1.2"
let buildCommit = "8db8147"
let buildBranch = "main"
let buildDate = "2026-04-24 10:40:23 UTC"
let buildSwiftVersion = "6.3"
let buildOS = "macOS 26.3.1"
