// Auto-generated by make — do not edit
let buildVersion = "0.8.8"
let buildCommit = "e8a5313"
let buildBranch = "main"
let buildDate = "2026-04-06 12:09:20 UTC"
let buildSwiftVersion = "6.3"
let buildOS = "macOS 26.3"
