// Auto-generated by make — do not edit
let buildVersion = "0.9.5"
let buildCommit = "2c3549a"
let buildBranch = "main"
let buildDate = "2026-04-08 18:10:02 UTC"
let buildSwiftVersion = "6.3"
let buildOS = "macOS 26.3.1"
